services:
  - type: web
    name: telegram-reminder-bot
    runtime: python
    buildCommand: ""
    startCommand: bash start.sh
    envVars:
      - key: TOKEN
        value: 7621419938:AAEopXdj4UX-cmzjR_RcRoFjQKZgmOGriHI
